version: "3"
services:
        postgres:
                image: postgres:9.6.24
                restart: always
                environment:
                        POSTGRES_USER: postgresdocker
                        POSTGRES_PASSWORD: 1234567890
                ports:
                        - 5432:5432
                volumes: 
                        - ./data/postgresql:/var/lib/postgresql/data